### ISSUE TITLE
[Ancient bug reproduction]

### ISSUE THREAD

**Issue by ibookcc** [GenisysPro/GenisysPro#393]
# bug复现：

1. 对一个物品进行附魔（使用附魔台）或者修复（使用铁砧）
2. 附魔或修复结束取出
3. 物品会掉落到地面（未附魔的装备和附魔石）
4. 并且经验扣除

# bug reappearance:
1. of a product (using enchant enchant Taiwan) or repair (using the anvil)
2. enchant or repair, end, take out
3. items will fall to the ground (unenchanted equipment and attached felstone)
4. and empirical deductions

# GenisysPro.yml setting is

As is know to all, if you setting
` allow-cheats: true`
Player will can cheat in game to getting anything item.
So i false it(Obviously, this is not the way to solve the problem).
Here is what I set
```
enchantment:
 enable-anvil: true
 enable-enchanting-table: true
 count-bookshelf: true

inventory:
 allow-cheats: false
```

# environment

- 2017 x86_64
- PHP version: 7.0.9
- Zend version: 3.0.0
- OS : Linux, linux
- GenisysPro version: 0000000000000000000000000000000000000000 [Protocol 113; API 3.0.1]
